# Config Server — MUST start first (other services depend on it)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: movie-booking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: utkarshcoder1/movie-config-server:latest
          ports:
            - containerPort: 8888
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "384Mi"
              cpu: "300m"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8888
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8888
            initialDelaySeconds: 60
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: config-server
  namespace: movie-booking
spec:
  selector:
    app: config-server
  ports:
    - port: 8888
      targetPort: 8888
